name: Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest]
        java_version: [8, 11, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: ${{ matrix.java_version }}
    - name: Build with Maven
      run: mvn package --file pom.xml
